export enum EFunctionPermissionCode {
  /** WEB PORTAL */

  WEB_PORTAL = 'WEB_PORTAL',

  WEB_PORTAL__USER_MANAGEMENT = 'WEB_PORTAL__USER_MANAGEMENT',
  WEB_PORTAL__USER_MANAGEMENT__VIEW = 'WEB_PORTAL__USER_MANAGEMENT__VIEW',
  WEB_PORTAL__USER_MANAGEMENT__CREATE = 'WEB_PORTAL__USER_MANAGEMENT__CREATE',
  WEB_PORTAL__USER_MANAGEMENT__UPDATE = 'WEB_PORTAL__USER_MANAGEMENT__UPDATE',
  WEB_PORTAL__USER_MANAGEMENT__DELETE = 'WEB_PORTAL__USER_MANAGEMENT__DELETE',

  WEB_PORTAL__ACCOUNT_MANAGEMENT = 'WEB_PORTAL__ACCOUNT_MANAGEMENT',
  WEB_PORTAL__ACCOUNT_MANAGEMENT__VIEW = 'WEB_PORTAL__ACCOUNT_MANAGEMENT__VIEW',
  WEB_PORTAL__ACCOUNT_MANAGEMENT__CREATE = 'WEB_PORTAL__ACCOUNT_MANAGEMENT__CREATE',
  WEB_PORTAL__ACCOUNT_MANAGEMENT__UPDATE = 'WEB_PORTAL__ACCOUNT_MANAGEMENT__UPDATE',
  WEB_PORTAL__ACCOUNT_MANAGEMENT__DELETE = 'WEB_PORTAL__ACCOUNT_MANAGEMENT__DELETE',

  WEB_PORTAL__SHIFT_MANAGEMENT = 'WEB_PORTAL__SHIFT_MANAGEMENT',
  WEB_PORTAL__SHIFT_MANAGEMENT__VIEW = 'WEB_PORTAL__SHIFT_MANAGEMENT__VIEW',
  WEB_PORTAL__SHIFT_MANAGEMENT__CREATE = 'WEB_PORTAL__SHIFT_MANAGEMENT__CREATE',
  WEB_PORTAL__SHIFT_MANAGEMENT__UPDATE = 'WEB_PORTAL__SHIFT_MANAGEMENT__UPDATE',
  WEB_PORTAL__SHIFT_MANAGEMENT__DELETE = 'WEB_PORTAL__SHIFT_MANAGEMENT__DELETE',

  WEB_PORTAL__APPLICATION_MANAGEMENT = 'WEB_PORTAL__APPLICATION_MANAGEMENT',
  WEB_PORTAL__APPLICATION_MANAGEMENT__VIEW = 'WEB_PORTAL__APPLICATION_MANAGEMENT__VIEW',
  WEB_PORTAL__APPLICATION_MANAGEMENT__CREATE = 'WEB_PORTAL__APPLICATION_MANAGEMENT__CREATE',
  WEB_PORTAL__APPLICATION_MANAGEMENT__UPDATE = 'WEB_PORTAL__APPLICATION_MANAGEMENT__UPDATE',
  WEB_PORTAL__APPLICATION_MANAGEMENT__DELETE = 'WEB_PORTAL__APPLICATION_MANAGEMENT__DELETE',

  WEB_PORTAL__CONFIGURATION_MANAGEMENT = 'WEB_PORTAL__CONFIGURATION_MANAGEMENT',

  WEB_PORTAL__CONFIGURATION_MANAGEMENT__FUNCTION_PERMISSION = 'WEB_PORTAL__CONFIGURATION_MANAGEMENT__FUNCTION_PERMISSION',
  WEB_PORTAL__CONFIGURATION_MANAGEMENT__FUNCTION_PERMISSION__VIEW = 'WEB_PORTAL__CONFIGURATION_MANAGEMENT__FUNCTION_PERMISSION__VIEW',
  WEB_PORTAL__CONFIGURATION_MANAGEMENT__FUNCTION_PERMISSION__CREATE = 'WEB_PORTAL__CONFIGURATION_MANAGEMENT__FUNCTION_PERMISSION__CREATE',
  WEB_PORTAL__CONFIGURATION_MANAGEMENT__FUNCTION_PERMISSION__UPDATE = 'WEB_PORTAL__CONFIGURATION_MANAGEMENT__FUNCTION_PERMISSION__UPDATE',
  WEB_PORTAL__CONFIGURATION_MANAGEMENT__FUNCTION_PERMISSION__DELETE = 'WEB_PORTAL__CONFIGURATION_MANAGEMENT__FUNCTION_PERMISSION__DELETE',

  WEB_PORTAL__CONFIGURATION_MANAGEMENT__DATA_PERMISSION = 'WEB_PORTAL__CONFIGURATION_MANAGEMENT__DATA_PERMISSION',
  WEB_PORTAL__CONFIGURATION_MANAGEMENT__DATA_PERMISSION__VIEW = 'WEB_PORTAL__CONFIGURATION_MANAGEMENT__DATA_PERMISSION__VIEW',
  WEB_PORTAL__CONFIGURATION_MANAGEMENT__DATA_PERMISSION__CREATE = 'WEB_PORTAL__CONFIGURATION_MANAGEMENT__DATA_PERMISSION__CREATE',
  WEB_PORTAL__CONFIGURATION_MANAGEMENT__DATA_PERMISSION__UPDATE = 'WEB_PORTAL__CONFIGURATION_MANAGEMENT__DATA_PERMISSION__UPDATE',
  WEB_PORTAL__CONFIGURATION_MANAGEMENT__DATA_PERMISSION__DELETE = 'WEB_PORTAL__CONFIGURATION_MANAGEMENT__DATA_PERMISSION__DELETE',

  /** ATTENDANCE APP */

  ATTENDANCE_APP = 'ATTENDANCE_APP',

  ATTENDANCE_APP__ATTENDANCE = 'ATTENDANCE_APP__ATTENDANCE',
  ATTENDANCE_APP__ATTENDANCE__WIFI = 'ATTENDANCE_APP__ATTENDANCE__WIFI',
}
